version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: iothub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iothubdb
    ports:
      - "5433:5432"
    volumes:
      - iothub_pg_data:/var/lib/postgresql/data
volumes:
  iothub_pg_data: